// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mvcapppojisteniverze02.Data;

#nullable disable

namespace mvcapppojisteniverze02.Migrations
{
    [DbContext(typeof(mvcapppojisteniverze02Context))]
    [Migration("20220815151406_uvodni_inicializace")]
    partial class uvodni_inicializace
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("mvcapppojisteniverze02.Models.Klient", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mesto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Psc")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("Telefon")
                        .HasColumnType("int");

                    b.Property<string>("Ulice")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("ID");

                    b.ToTable("Klienti");
                });

            modelBuilder.Entity("mvcapppojisteniverze02.Models.Produkt", b =>
                {
                    b.Property<int>("ProduktID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProduktID"), 1L, 1);

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Popis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProduktID");

                    b.ToTable("Produkty");
                });

            modelBuilder.Entity("mvcapppojisteniverze02.Models.ZaznamPojisteni", b =>
                {
                    b.Property<int>("ZaznamPojisteniID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZaznamPojisteniID"), 1L, 1);

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<int>("KlientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("KonecPojisteni")
                        .HasColumnType("datetime2");

                    b.Property<string>("PredmetPojisteni")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("ProduktID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ZacatekPojisteni")
                        .HasColumnType("datetime2");

                    b.HasKey("ZaznamPojisteniID");

                    b.HasIndex("KlientID");

                    b.HasIndex("ProduktID");

                    b.ToTable("ZaznamyPojisteni");
                });

            modelBuilder.Entity("mvcapppojisteniverze02.Models.ZaznamPojisteni", b =>
                {
                    b.HasOne("mvcapppojisteniverze02.Models.Klient", "Klient")
                        .WithMany("ZaznamPojisteniKolekce")
                        .HasForeignKey("KlientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mvcapppojisteniverze02.Models.Produkt", "Produkt")
                        .WithMany("ZaznamPojisteniKolekce")
                        .HasForeignKey("ProduktID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klient");

                    b.Navigation("Produkt");
                });

            modelBuilder.Entity("mvcapppojisteniverze02.Models.Klient", b =>
                {
                    b.Navigation("ZaznamPojisteniKolekce");
                });

            modelBuilder.Entity("mvcapppojisteniverze02.Models.Produkt", b =>
                {
                    b.Navigation("ZaznamPojisteniKolekce");
                });
#pragma warning restore 612, 618
        }
    }
}
